daisybio/DIGGER

- README.md
- docker-compose.yml
- domain/Process/exonstodomain.py
- domain/Process/gene.py
- domain/Process/network_analysis.py
- domain/Process/process_data.py
- domain/Process/transcript.py
- domain/autocomplete.py
- domain/management/commands/import_datasets.py
- domain/static/domain/organism_selector.js
- domain/static/domain/typeahead.js
- domain/templates/setup/exon_level.html
- domain/templates/setup/isoform_level.html
- domain/templates/setup/network.html
- domain/urls.py
- domain/views.py
- templates/base.html
- Removed convoluted database access, replaced with simple SQL and extensible data tables
- Introduced new naming scheme for different organisms
- Dynamic access of organisms for easy extension
> Digger v1.4

- domain/static/domain/organism_selector.js
- domain/urls.py
- preprocess/graph_attributes.py
fixed issues with the get_organism endpoint where the site would request it from the absolute path rather than a relative path
> get_organisms bugfixes

- domain/Process/exon.py
- domain/templates/setup/exon_level.html
- domain/templates/setup/isoform_level.html
- domain/templates/setup/network.html
- domain/templates/visualization/exon.html
- domain/templates/visualization/network.html
- domain/templates/visualization/transcript.html
- domain/views.py
- static/css/general.css
- templates/about.html
- templates/base.html
- templates/base_information.html
- templates/documentation.html
- templates/download.html
- templates/home.html
bugfixes
updated website design
> Digger v1.6

- domain/Process/gene.py
- domain/Process/network_analysis.py
- domain/Process/transcript.py
- domain/static/domain/exampleSelector.js
- domain/templates/setup/exon_level.html
- domain/templates/setup/isoform_level.html
- domain/templates/visualization/exon.html
- domain/templates/visualization/gene.html
- domain/templates/visualization/transcript.html
- preprocess/missing_gene_symbols.py
- static/css/general.css
small bugfixes,
added warning for longer wait times, 
styling
> Digger v1.6.1

- container/domain/templates/visualization/exon.html
- container/domain/templates/visualization/transcript.html
- container/domain/views.py
bug prevented some networks from being rendered
> bugfix: missing color

- README.md
- container/domain/nease/functions.py
- container/domain/nease/nease.py
- container/domain/nease/process.py
- container/domain/static/domain/initStore.js
- container/domain/static/domain/loadStore.js
- container/domain/templates/setup/nease_setup.html
- container/domain/templates/visualization/exon.html
- container/domain/templates/visualization/nease_result.html
- container/domain/templates/visualization/transcript.html
- container/domain/views.py
- container/templates/about.html
- container/templates/base.html
- container/templates/documentation.html
- container/templates/download.html
- container/templates/home.html
- docker/web/Dockerfile
- docs/README.md
- docs/index.html
Added bugfixes, minor cosmetic improvements and some more error handling to be ready for release:
- added wait disclaimer when visualising pathways 
- added back button (to get to selection menu)
- added disclaimer for bigger files
- available databases now as a list on the side
- visualization plot in edge enrichment now updates
- removed classic enrichment
- proper conversion to gene names in tables
- more visible tooltips
- github pages for documentation
- fixed path analysis output
> Fix up website for release

- container/domain/nease/functions.py
- container/domain/nease/nease.py
- container/domain/nease/process.py
- container/domain/templates/setup/nease_setup.html
- container/domain/templates/visualization/nease_result.html
- container/domain/tmp.py
This round of fixes mainly addresses the proper translation of different IDs. This is now significantly faster and also uses fewer online-lookups.
> round 3 of fixes

- container/domain/Process/nease_output.py
- container/domain/nease/nease.py
- container/domain/nease/process.py
- container/domain/templates/setup/nease_setup.html
- container/domain/templates/visualization/nease_result.html
- container/domain/views.py
Minor round, mostly type casting and enuring proper format handling
> Round 4 of bug fixes

- container/domain/Process/nease_output.py
- container/domain/nease/functions.py
- container/domain/nease/nease.py
- container/domain/nease/process.py
- container/domain/templates/visualization/nease_result.html
- container/domain/tmp.py
- container/domain/views.py
Some light documentation especially in the view.py file to better understand where the requests are going.
Also, some TODOs that need to be taken care of before release.
> Added some light documentation

- container/domain/Process/exonstodomain.py
- container/domain/Process/proteininfo.py
- container/domain/Process/transcript.py
- container/domain/templates/setup/nease_setup.html
- container/domain/views.py
- docker/web/Dockerfile
- docker/web/auto_clean.sh
This PR mainly addresses #28. 
Also some logs + minor bugfixes for the previous analysis mechanic.
> Force add residue supported PPIs + minor bugfixes

- container/domain/nease/functions.py
- container/domain/nease/nease.py
- container/domain/templates/visualization/nease_result.html
This PR aims to improve the pathway visualisation. Concrete changes:
- make background white to be more in style with the rest of the site
- add dropdown menu so to hide background edges that only obstruct view (fixes #30) 
- move legend away from graph for better visibility
- give better instructions on what `k` refers to in the parameters
> Improvements to pathway visualisation

- container/domain/templates/setup/nease_setup.html
- container/domain/templates/visualization/nease_result.html
Changed the default min delta value for whippet files while also alerting the user in case they want to use a different value.
Fixes #32
> Change default min delta value for Whippet input

- container/DomainExplorer/settings/common.py
- container/domain/Process/nease_output.py
- container/domain/nease/process.py
- container/domain/templates/visualization/nease_result.html
- container/domain/views.py
This PR adjusts the DataTables displayed on the website. 
- Tables are now more web-friendly with links to external databases and reduced redundancy
- Tables now fit better to the width of the container while still being proper DataTables
The downloadable tables stay the same as any web-modification happens after saving of the tables.
This PR fixes #26
> Adjusting the data tables

- container/domain/nease/functions.py
- container/domain/nease/nease.py
- container/domain/nease/process.py
- container/domain/views.py
This adresses  #24 and a little bit of #31 though for that we should put in some more work.
> Update pie chart and improve error messages

- container/domain/static/domain/organism_selector.js
- container/domain/templates/setup/nease_setup.html
Added example data from the original NEASE tutorial that gets pulled with the click of a button. Also some UX improvements.
> Add example data for publication

- container/domain/nease/functions.py
- docker-compose.yml
- docker/web/Dockerfile
- docker/web/start.sh
A few small bug fixes and a little bit more consistency.
> Bugfixes and improved consistency

- container/domain/templates/visualization/nease_result.html
> adding supported databases will not repeat ones, that have already been selected

- container/domain/Process/nease_output.py
- container/domain/nease/functions.py
- container/domain/templates/setup/nease_setup.html
- container/domain/templates/visualization/nease_result.html
- container/domain/templates/visualization/transcript.html
- container/domain/views.py
- container/templates/about.html
This fixes #62. And starts work on #65.
> Add thumbnail capability & prettier download icons

- container/domain/Process/nease_output.py
- container/domain/nease/functions.py
We now stick to one theme and the colors should work together. I am not entirely convinced by the orange in the bar plot but we can open another issue if we want to work on it again.
> Improve output visualisations

- preprocess/main_ddi_extend.py
- preprocess/predict_interactions/parse_yaml.py
Since I had to redo the PPI/DDI graph I also had to fix multiple bugs I found. This PR fixes these bugs so that this part of DIGGER also works better.
> Fix multiple bugs in DDI extension part

- container/domain/templates/setup/nease_setup.html
- container/domain/templates/visualization/nease_result.html
This PR aims to fix #59. Since we can't just edit the nginx conf (and that would be difficult anyway) I tried to do this JS implementation. I am unable to test it locally, but it should probably work.
> redirect on www. subdomain

- container/domain/nease/nease.py
- container/domain/views.py
Copy all objects needed by nease such that the original objects will not be edited - this may solve the unreliability issues we were experiencing.
> Copy by value

- container/domain/nease/nease.py
Forgot this one in my last PR.
> Copy network graph also

- container/domain/nease/functions.py
- container/domain/nease/nease.py
This change only shows in the output logs but ensures more consistency across the analysis.
> Proper use of supported graphs

- docs/README.md
Standard input description added
Some FAQ added
> Documentation update

- container/domain/templates/setup/nease_setup.html
- container/domain/templates/visualization/nease_result.html
- container/templates/home.html
This PR improves some small UX points:
1. Sort the Previous Analyses by creation date such that the newest analyses are at the top.
2. Add a banner at the bottom of the main page indicating that DIGGER 2.0 is free to use (as per NAR requirements).
3. Made the “Spliced genes” column collapsable so that it doesn't take up too much space. Adds #81.
> Improve UX

- container/domain/templates/setup/nease_setup.html
Only sort when there are at least two previous analyses available
> Fix sorting

- container/domain/Process/nease_output.py
- container/domain/nease/annotated_graph.py
- container/domain/nease/functions.py
- container/domain/nease/load.py
- container/domain/nease/nease.py
- container/domain/templates/visualization/nease_result.html
- container/domain/views.py
Implements #90, Fixes #91 and sets a file size limit of 100MB to prevent people from crashing the server with very large files.
> Add Pathway network visualisation

- container/domain/templates/setup/nease_setup.html
- container/domain/templates/visualization/nease_result.html
- container/domain/urls.py
This PR:
- moves the admin page to prevent some automated attack scripts
- improves the styling of the input information button
- reverts the min delta if whippet is deselected
> Improved UI styling

- container/domain/templates/visualization/no_info.html
- container/domain/urls.py
- container/domain/views.py
- docs/README.md
With this PR we:
- provide support for legacy DIGGER links via redirects
- provide a stylised output when no data is available (see image below)
- include an FAQ question about rMATS formats
> Polishing updates

- container/domain/templates/setup/nease_setup.html
To make it a bit more clear that processing is going on, this is the new loading overlay. Example screenshot:
> New loading overlay

- container/domain/nease/nease.py
- container/domain/nease/process.py
- container/domain/templates/setup/nease_setup.html
- container/domain/templates/visualization/nease_result.html
Errors are more useful now + added description on then network vis for the edges
> Slight improvements to error handling

- container/domain/nease/functions.py
> Some connections in the pathway vis were missing due them not being added to the initial graph
